services:
  postgres:
    image: postgres:latest
    container_name: geb_postgres
    environment:
      POSTGRES_DB: geb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_geb:/var/lib/postgresql

volumes:
  postgres_data_geb:
